const data = [
    {
        active: true,
        id: "neurologic",
        title: "Neurologic<sup>1,6,19</sup>",
        word: "Neurologic",
        icon: "/assets/images/hpp-profile/skeleton/neurologic-icon-active.svg",
        text: "Fatigue, headache, sleep disturbances",
        image1: "/assets/images/hpp-profile/skeleton/neurologic-img.png",
        imageAlt1: "Neurologic image",
        image2: "",
        imageAlt2: "",
        condition: "",
        type: "adults",
    },
    {
        active: true,
        id: "neurologic--infants",
        title: "Neurologic<sup>1,6,19</sup>",
        word: "Neurologic",
        icon: "/assets/images/hpp-profile/skeleton/neurologic-icon-active.svg",
        text: "Fatigue, headache, sleep disturbances",
        image1: "/assets/images/hpp-profile/skeleton/neurologic-img.png",
        imageAlt1: "Neurologic image",
        image2: "",
        imageAlt2: "",
        condition: "",
        type: "infants",
    },
    {
        active: false,
        id: "dental",
        title: "Dental<sup>1,9</sup>",
        word: "Dental",
        icon: "/assets/images/hpp-profile/skeleton/dental-icon-active.svg",
        text: "Premature tooth loss with root intact, abnormal dentition, periodontal disease",
        image1: "/assets/images/hpp-profile/skeleton/dental-img.png",
        imageAlt1: "Dental x-ray one",
        image2: "",
        imageAlt2: "",
        condition:
            "Reproduced with permission from Bloch-Zupan A. <em>Int Jour Paedtr Dent. 2016;26:426-438 and Reibel A. Orphanet J Rare Dis. 2009;4:6.</em>",
        type: "adults",
    },
    {
        active: false,
        id: "dental--infants",
        title: "Dental<sup>1,9</sup>",
        word: "Dental",
        icon: "/assets/images/hpp-profile/skeleton/dental-icon-active.svg",
        text: "Premature tooth loss with root intact, abnormal dentition, periodontal disease",
        image1: "/assets/images/hpp-profile/skeleton/dental-xray-one.png",
        imageAlt1: "Dental x-ray one",
        image2: "/assets/images/hpp-profile/skeleton/dental-xray-two.png",
        imageAlt2: "Dental x-ray two",
        condition:
            "Reproduced with permission from Bloch-Zupan A. <em>Int Jour Paedtr Dent. 2016;26:426-438 and Reibel A. Orphanet J Rare Dis. 2009;4:6.</em>",
        type: "infants",
    },
    {
        active: false,
        id: "muscular",
        title: "Muscular<sup>1,9,10,18</sup>",
        word: "Muscular",
        icon: "/assets/images/hpp-profile/skeleton/muscular-icon-active.svg",
        text: "Symptoms include muscle weakness, pain, waddling gait, difficulty walking, reduced grip force assessed by digital hand dynamometer",
        image1: "/assets/images/hpp-profile/skeleton/muscular-img.png",
        imageAlt1: "Muscular image",
        image2: "",
        imageAlt2: "",
        condition: "Jandl NM. <em>Calcif Tissue Int.</em> 2021;108(3):288-301.",
        type: "adults",
    },
    {
        active: false,
        id: "muscular--infants",
        word: "Muscular",
        title: "Muscular<sup>1,9,10,18</sup>",
        icon: "/assets/images/hpp-profile/skeleton/muscular-icon-active.svg",
        text: "Symptoms include muscle weakness, pain, waddling gait, difficulty walking, reduced grip force assessed by digital hand dynamometer",
        image1: "/assets/images/hpp-profile/skeleton/muscular-img.png",
        imageAlt1: "Muscular image",
        image2: "",
        imageAlt2: "",
        condition: "Jandl NM. <em>Calcif Tissue Int.</em> 2021;108(3):288-301.",
        type: "infants",
    },
    {
        active: false,
        id: "respiratory--infants",
        title: "Respiratory<sup>9</sup>",
        word: "Respiratory",
        icon: "/assets/images/hpp-profile/skeleton/respiratory-icon-active.svg",
        text: "History of respiratory support",
        image1: "/assets/images/hpp-profile/skeleton/respiratory-img.png",
        imageAlt1: "Respiratory image",
        image2: "",
        imageAlt2: "",
        condition: " <p> “Bell-shape” configuration of the soft thorax will predispose to respiratory disease.</p> <p>Reproduced with permission from Whyte MP. Hypophosphatasia: nature’s window on alkaline phosphatase function in humans. In: <em>Principles of Bone Biology.</em> 3rd ed. Academic Press; 2008:1573-1598.</p>",
        type: "infants",
    },
    {
        active: false,
        id: "rheumatic",
        title: "Rheumatic<sup>1,6,9,11-14</sup>",
        word: "Rheumatic",
        icon: "/assets/images/hpp-profile/skeleton/rheumatic-icon-active.svg",
        text: "Calcific periarthritis, chondrocalcinosis, fibromyalgia, pain, pseudogout, osteoarthritis, rheumatoid arthritis, spondyloarthritis, and collagenosis",
        image1: "/assets/images/hpp-profile/skeleton/rheumatic-img.png",
        imageAlt1: "Rheumatic image",
        image2: "",
        imageAlt2: "",
        condition:
            "Hogler W. <em>BMC Musculoskeletal Disorders.</em> 2019;29(1):80-88. Feurstein J. <em>Orphanet J Rare Dis.</em> 2022;17(1):435-442.",
        type: "adults",
    },
    {
        active: false,
        id: "rheumatic--infants",
        title: "Rheumatic<sup>1,6,9,11-14</sup>",
        word: "Rheumatic",
        icon: "/assets/images/hpp-profile/skeleton/rheumatic-icon-active.svg",
        text: "Calcific periarthritis, chondrocalcinosis, fibromyalgia, pain, pseudogout, osteoarthritis, rheumatoid arthritis, spondyloarthritis, and collagenosis",
        image1: "/assets/images/hpp-profile/skeleton/rheumatic-img.png",
        imageAlt1: "Rheumatic image",
        image2: "",
        imageAlt2: "",
        condition:
            "Hogler W. <em>BMC Musculoskeletal Disorders.</em> 2019;29(1):80-88. Feurstein J. <em>Orphanet J Rare Dis.</em> 2022;17(1):435-442.",
        type: "infants",
    },
    {
        active: false,
        id: "renal",
        title: "Renal<sup>3,6,10</sup>",
        word: "Renal",
        icon: "/assets/images/hpp-profile/skeleton/renal-icon-active.svg",
        text: "History of hypercalcemia, hyperphosphatemia, kidney stones, and nephrocalcinosis",
        image1: "/assets/images/hpp-profile/skeleton/renal-img.png",
        imageAlt1: "Renal image",
        image2: "",
        imageAlt2: "",
        condition:"",
        type: "adults",
    },
    {
        active: false,
        id: "renal--infants",
        title: "Renal<sup>3,6,10</sup>",
        word: "Renal",
        icon: "/assets/images/hpp-profile/skeleton/renal-icon-active.svg",
        text: "History of hypercalcemia, hyperphosphatemia, kidney stones, and nephrocalcinosis",
        image1: "/assets/images/hpp-profile/skeleton/renal-img.png",
        imageAlt1: "Renal image",
        image2: "",
        imageAlt2: "",
        condition:"",
        type: "infants",
    },
    {
        active: false,
        id: "orthopedic",
        title: "Orthopedic/skeletal<sup>1,3,9,14,17</sup>",
        word: "Orthopedic/ Skeletal",
        icon: "/assets/images/hpp-profile/skeleton/orthopedic-icon-active.svg",
        text: "Fractures, pseudofractures, rickets/osteomalacia, osteopenia, severe hypomineralization, bone/joint pain, skeletal deformities",
        image1: "/assets/images/hpp-profile/skeleton/orthopedic-img.png",
        imageAlt1: "Orthopedic image",
        image2: "",
        imageAlt2: "",
        condition: "Bianchi ML.<em> Osteoporos Int.</em> 2020;31(8):1445-1460.",
        type: "adults",
    },
    {
        active: false,
        id: "orthopedic--infants",
        title: "Orthopedic/skeletal<sup>1,3,9,14,17</sup>",
        word: "Orthopedic/ Skeletal",
        icon: "/assets/images/hpp-profile/skeleton/orthopedic-icon-active.svg",
        text: "Fractures, pseudofractures, rickets/osteomalacia, osteopenia, severe hypomineralization, bone/joint pain, skeletal deformities",
        image1: "/assets/images/hpp-profile/skeleton/orthopedic-img.png",
        imageAlt1: "Orthopedic image",
        image2: "",
        imageAlt2: "",
        condition: "Bianchi ML.<em> Osteoporos Int.</em> 2020;31(8):1445-1460.",
        type: "infants",
    },
    {
        active: false,
        id: "developmental--infants",
        title: "Developmental/growth<sup>11,13</sup>",
        word: "Developmental/ Growth",
        icon: "/assets/images/hpp-profile/skeleton/developmental-icon-active.svg",
        text: "Short stature, failure to thrive, poor weight gain, and delayed or missed motor milestones",
        image1: "/assets/images/hpp-profile/skeleton/developmental-img.png",
        imageAlt1: "Developmental image",
        image2: "",
        imageAlt2: "",
        condition: "<p>Flared wrists are indicative of rachitic widening, with rickets associated with short stature and delayed walking.</p> <p>Reproduced with permission from Whyte MP. <em>Genetics of Bone Biology and Skeletal Disease.</em> 2013; 337-360.</p>",
        type: "infants",
    },
];

export default data;